import type { Metadata } from "next";
import "./globals.css";
import { Header } from "@/src/shared/ui/Header";
import { NavBar } from "@/src/widgets/navBar/ui/NavBar";
import { Footer } from "@/src/shared/ui/Footer";
import { jetBrainsMono } from "@/src/shared/config";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`h-screen p-2 ${jetBrainsMono.className}`}>
        <div className="border-solid border-2 border-white flex flex-col p-4 h-full">
          <Header />
          <NavBar />
          <main className="flex-2">{children}</main>
          <Footer />
        </div>
      </body>
    </html>
  );
}
